Added unit-smoke tests for DB connection

diff --git a/.github/workflows/ci_cd_pipeline_db_connection.yml b/.github/workflows/ci_cd_pipeline_db_connection.yml
--- a/.github/workflows/ci_cd_pipeline_db_connection.yml
+++ b/.github/workflows/ci_cd_pipeline_db_connection.yml
@@ -20,14 +20,60 @@ jobs:
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
-    - name: Build and push Docker image
+    - name: Build and push Docker images
       run: |
         cd _2_services/db_connection/docker
-        docker build -t fberton98/db_connection:latest .
+        docker build -t fberton98/db_connection:test .
+        docker push fberton98/db_connection:test
+
+  unit-tests:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v3
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Run Unit Tests
+      run: |
+        docker run --rm fberton98/db_connection:test python -m unittest discover -s /app || { echo 'Unit tests failed'; exit 1; }    
+    - name: Tag and push image if tests pass
+      if: success()
+      run: |
+        docker tag fberton98/db_connection:test fberton98/db_connection:latest
         docker push fberton98/db_connection:latest
+
+  cluster-test:
+    runs-on: ubuntu-latest
+    needs: unit-tests
+    steps:
+    - name: Install sshpass
+      run: sudo apt-get install -y sshpass
+    - name: Test Deployment
+      env:
+        SSH_USER: ${{ secrets.SSH_USER }}
+        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
+        SSH_HOST: ${{ secrets.SSH_HOST }}
+        SSH_PORT: ${{ secrets.SSH_PORT }}
+      run: |
+        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<EOF
+          set -e
+          cd k8_healtcare_cluster/_2_services/db_connection/test
+          kubectl apply -f deployment_service_test.yaml
+          trap 'kubectl delete -f deployment_service_test.yaml' EXIT
+          kubectl wait --for=condition=available --timeout=600s deployment/db-connection-deployment-test
+          kubectl wait --for=condition=ready pod -l app=db-connection-deployment-test --timeout=600s
+          python3 smoke_test.py
+        EOF
 
   deploy:
     runs-on: ubuntu-latest
+    needs: cluster-test
     steps:
     - name: Install sshpass
       run: sudo apt-get install -y sshpass
