Creating daily test

diff --git a/.github/workflows/daily_test.yml b/.github/workflows/daily_test.yml
--- a/.github/workflows/daily_test.yml
+++ b/.github/workflows/daily_test.yml
@@ -2,7 +2,7 @@ name: Daily test
 
 on:
   schedule:
-    - cron: '20 12 * * *'  # Esegui ogni giorno alle 12:13 UTC
+    - cron: '00 00 * * *'
   workflow_dispatch:
 
 jobs:
@@ -13,10 +13,47 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Setup ambiente di test
+      - name: Setup test environment
         run: |
-          echo "Setup dell'ambiente di test"  # Comandi reali qui
+          echo "Setting up the test environment"  # Replace with actual setup commands
 
-      - name: Esegui i test
+      - name: Run tests
         run: |
-          echo "Esecuzione dei test"  # Inserisci qui i comandi di test
+          # Perform a POST request to http://epilepsy-prediction-service/predict with JSON data
+          response=$(curl -k -s -X POST http://epilepsy-prediction-service/predict \
+            -H "Content-Type: application/json" \
+            -d '{"eeg_data": [12,24,3,47,5,69,7,8,1,1,1,1,1,1,1,1,1,1,112,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,812,24,3,47,5,69,7,8]}')
+
+          # Extract HTTP response code
+          http_code=$(echo "$response" | head -n1)
+
+          # Extract JSON response message and response value
+          message=$(echo "$response" | jq -r '.message')
+          response_value=$(echo "$response" | jq -r '.response')
+
+          # Check if the HTTP response code is 200
+          if [ "$http_code" -eq 200 ]; then
+            echo "POST request succeeded"
+            
+            # Check if the JSON response message is "Received"
+            if [ "$message" == "Received" ]; then
+              echo "Response message is correct: $message"
+              
+              # Check if the response value is within an expected range
+              if (( $(echo "$response_value > 0" | bc -l) && $(echo "$response_value < 0.01" | bc -l) )); then
+                echo "Response value is within the expected range: $response_value"
+              else
+                echo "Response value is out of the expected range: $response_value"
+                exit 1
+              fi
+            else
+              echo "Response message is incorrect: $message"
+              exit 1
+            fi
+          else
+            echo "POST request failed with HTTP code: $http_code"
+            exit 1
+          fi
+
+          echo "All tests passed"
+
